-- =============================================
-- Migration V9: Create Image Tables
-- Social Studio IA - Image Management
-- H2 Compatible Version
-- =============================================

-- Table: imagens
-- Stores uploaded images with AI processing capabilities
CREATE TABLE IF NOT EXISTS imagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL,
    criador_id BIGINT NOT NULL,
    url_original VARCHAR(1000) NOT NULL,
    url_atual VARCHAR(1000),
    thumbnail_url VARCHAR(1000),
    nome_arquivo VARCHAR(100) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    tipo_mime VARCHAR(50) NOT NULL,
    largura INT NOT NULL,
    altura INT NOT NULL,
    descricao VARCHAR(200),
    total_versoes INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_imagem_salon FOREIGN KEY (salon_id) REFERENCES salons(id) ON DELETE CASCADE,
    CONSTRAINT fk_imagem_criador FOREIGN KEY (criador_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Indexes for imagens
CREATE INDEX IF NOT EXISTS idx_imagem_salon ON imagens(salon_id);
CREATE INDEX IF NOT EXISTS idx_imagem_criador ON imagens(criador_id);
CREATE INDEX IF NOT EXISTS idx_imagem_criado_em ON imagens(criado_em);
CREATE INDEX IF NOT EXISTS idx_imagem_ativo ON imagens(ativo);

-- Table: imagem_versoes
-- Stores edit history of images (each AI operation creates a version)
CREATE TABLE IF NOT EXISTS imagem_versoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagem_id BIGINT NOT NULL,
    url VARCHAR(1000) NOT NULL,
    operacao VARCHAR(50) NOT NULL,
    parametros VARCHAR(200),
    tamanho_bytes BIGINT NOT NULL,
    largura INT NOT NULL,
    altura INT NOT NULL,
    numero_versao INT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_versao_imagem FOREIGN KEY (imagem_id) REFERENCES imagens(id) ON DELETE CASCADE
);

-- Indexes for imagem_versoes
CREATE INDEX IF NOT EXISTS idx_versao_imagem ON imagem_versoes(imagem_id);
CREATE INDEX IF NOT EXISTS idx_versao_criado_em ON imagem_versoes(criado_em);
