apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: belezza
  labels:
    app: redis
    app.kubernetes.io/part-of: belezza
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
