apiVersion: v1
kind: Service
metadata:
  name: belezza-frontend
  namespace: belezza
  labels:
    app: belezza-frontend
    app.kubernetes.io/part-of: belezza
spec:
  type: ClusterIP
  selector:
    app: belezza-frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
